name: ksn_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - scipy
  - laspy
  - lazrs-python
  - numpy
  - pandas
  - requests
  - rasterio
  - shapely
  - whitebox
  - geopandas
  - matplotlib
  - pip:
      - python-dotenv
