name: ksn_env
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - scipy
  - laspy
  - lazrs-python
  - numpy
  - pandas
  - pdal
  - rasterio
  - shapely
  - whitebox
  - geopandas
  - matplotlib
  - pip:
      - python-dotenv
