name: ksn_env
channels:
  - esri
  - conda-forge
  - defaults
dependencies:
  - python=3.11 # Or whatever version your ArcGIS Pro uses
  - scipi
  - laspy
  - numpy
  - pandas
  - pdal
  - rasterio
  - scipi
  - shapely
  - whitebox
  - pip:
      - python-dotenv
